[package]
name = "learn-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
lofty = "0.22.4"
rodio = "0.21.1"
sqlx = {version = "0.8.6", features = ["postgres", "runtime-tokio-rustls", "chrono"]}
tokio = {version = "1.48.0", features = ["full"]}
